# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


class TestTestajaxdemo():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()
    
  def test_drag_drop(self):
      self.driver.get("https://demo.guru99.com/test/drag_drop.html")
      self.driver.maximize_window()
      dragged = self.driver.find_element(By.XPATH, "//*[@id=\"fourth\"]/a")
      dropped = self.driver.find_element(By.XPATH, "//*[@id=\"shoppingCart4\"]/div")
      actions = ActionChains(self.driver)
      actions.drag_and_drop(dragged, dropped).perform()
      assert self.driver.find_element(By.XPATH, "//*[@id=\"amt7\"]/li").text == "5000"
