# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC


class TestTestajaxdemo():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_testajaxdemo(self):
    self.driver.get("https://demo.guru99.com/")
    self.driver.find_element(By.LINK_TEXT, "Selenium").click()
    self.driver.find_element(By.LINK_TEXT, "Ajax Demo").click()
    self.driver.find_element(By.ID, "yes").click()
    self.driver.find_element(By.CSS_SELECTOR, "p > input:nth-child(1)").click()
    assert self.driver.find_element(By.ID, "yes").is_selected() is False
    assert self.driver.find_element(By.ID, "no").is_selected() is False
    self.driver.find_element(By.ID, "yes").click()
    self.driver.find_element(By.ID, "buttoncheck").click()
    assert self.driver.find_element(By.ID, "yes").is_selected() is True
    assert WebDriverWait(self.driver, 30).until(EC.text_to_be_present_in_element((By.CSS_SELECTOR, ".radiobutton"), "Radio button is checked and it\'s value is Yes"))
  
