# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.webdriver.support import expected_conditions as EC

class TestTestLogin():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def test_login(self):
        self.driver.get("https://www.demo.guru99.com/test/login.html")
        self.driver.maximize_window()
        self.driver.find_element(By.ID, "email").send_keys("test")
        self.driver.find_element(By.ID, "passwd").send_keys("test")
        self.driver.find_element(By.CSS_SELECTOR, "#SubmitLogin > span").click()

        element = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.XPATH, "/html/body/div[2]/div/div/h3"))
        )

        assert element.text == "Successfully Logged in..."