# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestDefaultSuite():
  def setup_method(self, method):
    self.driver = webdriver.Firefox()
    self.vars = {}
    self.wait = WebDriverWait(self.driver, 10)
  
  def teardown_method(self, method):
    self.driver.quit()

  def _dismiss_cookie_overlay(self):
    try:
      authorize_button = self.wait.until(
        expected_conditions.element_to_be_clickable(
          (By.XPATH, "//button[normalize-space()='Autoriser']")
        )
      )
      authorize_button.click()
    except Exception:
      self.driver.execute_script("""
      const dialog = document.querySelector('div[role="dialog"]');
      if (dialog) {
        dialog.remove();
      }
      document.querySelectorAll('.fc-dialog-scrollable-content').forEach((node) => node.remove());
      """)
    self.wait.until(lambda d: d.execute_script("return !document.querySelector('div[role=\"dialog\"]')"))
  
  def test_addition(self):
    self.driver.get("https://www.ma-calculatrice.fr/")
    self.driver.set_window_size(2016, 911)
    self._dismiss_cookie_overlay()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "toucheSept"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "btnAddition"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "toucheNeuf"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "btnEgale"))).click()
    assert self.driver.find_element(By.ID, "calculatriceTotalChiffre").text == "16"
  
  def test_division(self):
    self.driver.get("https://www.ma-calculatrice.fr/")
    self.driver.set_window_size(2016, 911)
    self._dismiss_cookie_overlay()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "toucheQuatre"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "btnDivision"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "toucheDeux"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "btnEgale"))).click()
    assert self.driver.find_element(By.ID, "calculatriceTotalChiffre").text == "2"
  
  def test_multiplication(self):
    self.driver.get("https://www.ma-calculatrice.fr/")
    self.driver.set_window_size(2016, 911)
    self._dismiss_cookie_overlay()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "toucheSept"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "btnMultiplication"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "toucheNeuf"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "btnEgale"))).click()
    assert self.driver.find_element(By.ID, "calculatriceTotalChiffre").text == "63"
  
  def test_soustraction(self):
    self.driver.get("https://www.ma-calculatrice.fr/")
    self.driver.set_window_size(2016, 911)
    self._dismiss_cookie_overlay()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "toucheSept"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "btnSoustraction"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "toucheDeux"))).click()
    self.wait.until(expected_conditions.element_to_be_clickable((By.ID, "btnEgale"))).click()
    assert self.driver.find_element(By.ID, "calculatriceTotalChiffre").text == "5"
  
