# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities
from selenium.common.exceptions import NoSuchElementException


class TestTestnbrko():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_testnbrko(self):
    self.driver.get("https://enijdenis.github.io/coffre")
    
    # Saisie du nombre de caractères -1
    self.driver.find_element(By.ID, "nb").click()
    self.driver.find_element(By.ID, "nb").send_keys("-1")
    
    # Sélectionner "minuscules"
    self.driver.find_element(By.ID, "min").click()
    
    # Cliquer sur le bouton Générer
    self.driver.find_element(By.ID, "generation").click()
    
    # Vérification qu'un message d'erreur s'affiche
    try:
      message = self.driver.find_element(By.ID, "message").text
    except NoSuchElementException:
      message = ""
    assert message != "", "BUG : aucun message d'erreur ne s'affiche"
