# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestnbrok():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_testnbrok(self):
    self.driver.get("https://enijdenis.github.io/coffre")
    
    # Saisie du nombre de caractères 12
    self.driver.find_element(By.ID, "nb").click()
    self.driver.find_element(By.ID, "nb").clear()
    self.driver.find_element(By.ID, "nb").send_keys("12")
    
    # Sélectionner "minuscules"
    self.driver.find_element(By.ID, "min").click()
    
    # Cliquer sur le bouton Générer
    self.driver.find_element(By.ID, "generation").click()
    
    # Lire le résultat dans le champ d'affichage
    mdp_genere = self.driver.find_element(By.ID, "mdp").text
    nb_caracteres = len(mdp_genere)
    
    #Vérification du résultat (Minuscule, longueur correcte)
    assert nb_caracteres == 12
    assert mdp_genere.islower()
    