# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestaccueil():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_testaccueil(self):
    self.driver.get("https://enijdenis.github.io/memory/index.html")
    self.driver.find_element(By.LINK_TEXT, "Accueil").click()
    
    WebDriverWait(self.driver, 10).until(expected_conditions.alert_is_present())
    alert = self.driver.switch_to.alert
    alert.accept()
    
    assert self.driver.find_element(By.CSS_SELECTOR, "p").text == "Bienvenue sur le site du Memory de l'ENI."
  
