# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestTestuserko():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_testuserko(self):
    self.driver.get("https://enijdenis.github.io/memory/index.html")
    self.driver.find_element(By.LINK_TEXT, "S\'inscrire").click()
    self.driver.find_element(By.ID, "user").click()
    self.driver.find_element(By.ID, "user").send_keys("te")
    self.driver.find_element(By.ID, "email").send_keys("test@test.com")
    self.driver.find_element(By.ID, "password").send_keys("Lagun@6806")
    self.driver.find_element(By.ID, "psw-confirmation").send_keys("Lagun@6806")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1)").click()
    assert self.driver.find_element(By.CSS_SELECTOR, ".input-group:nth-child(1) > .error-msg").text == "Choisissez un pseudo contenant au moins 3 caractères."
    WebDriverWait(self.driver, 2).until(expected_conditions.presence_of_element_located((By.CSS_SELECTOR, ".shake")))
  
