# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities


class TestNewTest():

  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}

  def teardown_method(self, method):
    self.driver.quit()

  def test_newTest(self):
    self.driver.get("https://enijdenis.github.io/memory/index.html")
    self.driver.find_element(By.LINK_TEXT, "S\'inscrire").click()
    self.driver.find_element(By.ID, "user").click()
    self.driver.find_element(By.ID, "user").send_keys("test")
    self.driver.find_element(By.ID, "email").send_keys("test@test.com")
    self.driver.find_element(By.ID, "password").send_keys("Lagun@6806")
    self.driver.find_element(By.ID, "psw-confirmation").send_keys("Lagun@6806")
    self.driver.find_element(By.CSS_SELECTOR, "button:nth-child(1)").click()

    WebDriverWait(self.driver, 10).until(expected_conditions.alert_is_present())
    alert = self.driver.switch_to.alert
    alert.accept()

    assert self.driver.title == "ENI-MEMORY-Connecter"
  
