# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.chrome.service import Service
from webdriver_manager.chrome import ChromeDriverManager

class TestDefaultSuite():
    def setup_method(self, method):
        self.driver = webdriver.Firefox()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    #Exercices 1 : Vérifier le titre de la page
    def test_textbox(self):
        self.driver.get("https://demo.guru99.com/")

        assert self.driver.title == "Guru99 Bank Home Page"

    #Exercices 2 : Login
    def test_login(self):
        self.driver.get("https://www.demo.guru99.com/test/login.html")
        self.driver.maximize_window()
        self.driver.find_element(By.ID, "email").send_keys("test")
        self.driver.find_element(By.ID, "passwd").send_keys("test")
        self.driver.find_element(By.CSS_SELECTOR, "#SubmitLogin > span").click()

        element = WebDriverWait(self.driver, 10).until(
            EC.presence_of_element_located((By.XPATH, "/html/body/div[2]/div/div/h3"))
        )

        assert element.text == "Successfully Logged in..."

    #Exercices 3 : Checkbox
    # Cliquer sur l'un des radiobouton puis cliquer sur le bouton ’Reset’
    # Tous les radioboutons sont déselectionnés
    def test_reset(self):
        self.driver.get("https://demo.guru99.com/test/ajax.html")
        # on sélectionne le bouton Yes
        self.driver.find_element(By.ID, "yes").click()
        # on clique sur le bouton reset
        self.driver.find_element(By.CSS_SELECTOR, "p > input:nth-child(1)").click()
        # Tous les radioboutons sont déselectionnés
        assert not self.driver.find_element(By.ID, "yes").is_selected()
        assert not self.driver.find_element(By.ID, "no").is_selected()

    #Cliquer le radiobouton ‘Yes’ puis sur le bouton ‘Check ‘
    # Un message s’affiche : “Radio button is checked and it's value is Yes”
    def test_submit(self):
        self.driver.get("https://demo.guru99.com/test/ajax.html")
        self.driver.find_element(By.ID, "yes").click()
        self.driver.find_element(By.ID, "buttoncheck").click()
        assert self.driver.find_element(By.ID, "yes").is_selected()
        assert self.driver.find_element(By.XPATH, "/html/body/div[2]/form/p[3]").text == \
               "Radio button is checked and it's value is Yes"

    #Exercices 4 : Drag and Drop
    def test_drag_drop(self):
        self.driver.get("https://demo.guru99.com/test/drag_drop.html")
        self.driver.maximize_window()
        dragged = self.driver.find_element(By.XPATH, "//*[@id=\"fourth\"]/a")
        dropped = self.driver.find_element(By.XPATH, "//*[@id=\"shoppingCart4\"]/div")
        actions = ActionChains(self.driver)
        actions.drag_and_drop(dragged, dropped).perform()
        assert self.driver.find_element(By.XPATH, "//*[@id=\"amt7\"]/li").text == "5000"
